title: LeBron James Is The Best
author: by Lachezar Dimitrov
email: lachezar_dimitrov@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  LeBron James is the best basketball player nowdays and he unanimously is called "The King".
# social links
instagram_username: lachezar_ddimitrov
github_username:  LachezarDimitrov

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
